title: Plataforma Forma
author: vintagenerd
email: vintagenerd@proton.mail
description: > # this means to ignore newlines until "baseurl:"
  Espaço para uma curta e sólida descrição do projeto. De momento é isto.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  vintagenerd # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
